-- Localization/deDE.lua
-- German locale. Only overrides; missing keys fall back to enUS.

local ADDON_NAME = ...
local L = LibStub("AceLocale-3.0"):NewLocale(ADDON_NAME, "deDE")
if not L then return end

L["General"] = "Allgemein"
L["Modules"] = "Module"
L["Enable, disable and configure each display element."] =
    "Jedes Anzeige-Element aktivieren, deaktivieren und konfigurieren."
L["HUD panel"] = "HUD-Panel"
-- Settings restructure (groups, About page, best-time bracket)
L["Settings"] = "Einstellungen"
L["Other"] = "Sonstiges"
L["Fonts"] = "Schrift"
L["Symbols"] = "Symbole"
L["Best times"] = "Bestzeiten"
L["Keystone level"] = "Schl\195\188sselsteinstufe"
L["Best time bracket"] = "Bestzeit-Klammer"
L["About"] = "\195\156ber"
L["Version"] = "Version"
L["Author"] = "Autor"
L["Commands"] = "Befehle"
L["License"] = "Lizenz"
L["Category"] = "Kategorie"
L["Command list"] = "/mauimpt \226\128\148 Optionen \195\182ffnen\n/mauimpt demo \226\128\148 Demo-Modus umschalten\n/mauimpt splits \226\128\148 Zeitenverwaltung \195\182ffnen\n/mauimpt checkpoints \226\128\148 Checkpoint-Editor \195\182ffnen\n/mauimpt changelog \226\128\148 Changelog \195\182ffnen\n/mauimpt setup \226\128\148 Setup-Assistent starten\n/mauimpt profiles \226\128\148 Profile \195\182ffnen"
L["No bracket"] = "Kein"
L["Credits"] = "Danksagungen"
L["Icon credit"] = "Symbole: Google Material Symbols (Apache-Lizenz 2.0)"
L["Sound credit"] = "Sounds: Sophia Conçeição, Universfield, freesound_community, Game Studio, juniorsoundays, Hanifi Şahin, Del, AlesiaDavina, Edimar Filho — von Pixabay (Pixabay Content License)"
L["Bar background color"] = "Balken-Hintergrundfarbe"
L["Fill direction"] = "Füllrichtung"
L["Row spacing"] = "Zeilenabstand"
L["Extra vertical space between objective rows."] =
    "Zusätzlicher vertikaler Abstand zwischen den Ziel-Zeilen."
L["Show best times"] = "Bestzeiten anzeigen"
L["Show the stored best run's split times behind each element during a run."] =
    "Zeigt die gespeicherten Zwischenzeiten der Bestzeit hinter jedem Element während eines Laufs."
L["Best time"] = "Bestzeit"
L["Best time size"] = "Bestzeit-Größe"
L["Best time bracket (left)"] = "Bestzeit-Klammer (links)"
L["Best time bracket (right)"] = "Bestzeit-Klammer (rechts)"
L["Character(s) shown before a best time. Leave empty for none."] =
    "Zeichen vor der Bestzeit. Leer = keins."
L["Character(s) shown after a best time. Leave empty for none."] =
    "Zeichen nach der Bestzeit. Leer = keins."
L["Left to right"] = "Links nach rechts"
L["Right to left"] = "Rechts nach links"
L["Comparison (+/-)"] = "Vergleich (+/-)"
L["Ahead of best"] = "Vor Bestzeit"
L["Behind best"] = "Hinter Bestzeit"
L["Max time color"] = "Farbe der Maximalzeit"
L["Show remaining count"] = "Verbleibende Anzahl anzeigen"
L["Show the remaining absolute mob count next to the percentage."] =
    "Zeigt die verbleibende absolute Gegnerzahl neben dem Prozentwert."
L["Defeated boss name"] = "Boss-Name (besiegt)"
L["Pending boss name"] = "Boss-Name (offen)"
L["Split time"] = "Abschnittszeit"
L["Time penalty color"] = "Farbe der Zeitstrafe"
L["Cooldown color"] = "Farbe der Abklingzeit"
L["Recharge color"] = "Farbe der Aufladezeit"
L["Remaining count color"] = "Farbe der verbleibenden Anzahl"
L["Show defeated icon"] = "Symbol für besiegt anzeigen"
L["Show pending icon"] = "Symbol für offen anzeigen"
L["Defeated icon"] = "Symbol (besiegt)"
L["Pending icon"] = "Symbol (offen)"
L["Death icon"] = "Tode-Symbol"
L["Heroism ready icon"] = "Heldentum-Bereit-Symbol"
L["Defeated icon color"] = "Symbolfarbe (besiegt)"
L["Pending icon color"] = "Symbolfarbe (offen)"
L["Death icon color"] = "Tode-Symbolfarbe"
L["Heroism ready icon color"] = "Heldentum-Bereit-Symbolfarbe"
L["Default"] = "Standard"
L["Automation"] = "Automatik"
L["Auto-hide objective tracker"] = "Quest-Tracker automatisch ausblenden"
L["Hide Blizzard's objective tracker while a Mythic+ run is active."] = "Blendet den Blizzard-Quest-Tracker aus, solange ein Mythisch+-Lauf aktiv ist."
L["Auto-slot keystone"] = "Schlüsselstein automatisch einlegen"
L["Automatically place your keystone when the Font of Power is opened."] = "Legt deinen Schlüsselstein automatisch ein, sobald das Quell der Macht geöffnet wird."
L["Dungeon icon"] = "Dungeon-Symbol"
L["Show dungeon icon"] = "Dungeon-Symbol anzeigen"
L["Icon position"] = "Symbol-Position"
L["Icon size"] = "Symbol-Größe"
L["Import / Export"] = "Import / Export"
L["Export"] = "Exportieren"
L["Import"] = "Importieren"
L["Export string"] = "Export-Text"
L["Click Export to generate a shareable string of your current profile, then copy it."] =
    "Auf Exportieren klicken, um einen teilbaren Text deines aktuellen Profils zu erzeugen, dann kopieren."
L["Paste a string and accept to import the profile. It is created under its exported name; your current profile is kept."] =
    "Text einfügen und bestätigen, um das Profil zu importieren. Es wird unter seinem exportierten Namen angelegt; dein aktuelles Profil bleibt erhalten."
L["Profile '%s' already exists. Overwrite it?"] =
    "Profil '%s' existiert bereits. Überschreiben?"
L["Imported profile '%s'."] = "Profil '%s' importiert."
L["Import failed: %s"] = "Import fehlgeschlagen: %s"
L["Debug mode"] = "Debug-Modus"
L["Show debug messages in chat."] = "Debug-Nachrichten im Chat anzeigen."
L["Demo mode"] = "Demo-Modus"
L["Show sample data so the display can be positioned and styled."] =
    "Beispieldaten anzeigen, um die Anzeige zu positionieren und zu gestalten."
L["Lock display"] = "Anzeige sperren"
L["Prevent the display from being dragged."] = "Verhindert das Verschieben der Anzeige."
L["Width"] = "Breite"
L["Width of the display in pixels (increase if text is cut off)."] =
    "Breite der Anzeige in Pixeln (erhöhen, falls Text abgeschnitten wird)."
L["Element spacing"] = "Abstand zwischen Elementen"
L["Vertical gap between the stacked HUD elements (e.g. between the timer and forces bars)."] =
    "Vertikaler Abstand zwischen den gestapelten HUD-Elementen (z. B. zwischen Timer- und Streitkräfte-Balken)."
L["Separator lines"] = "Trennlinien"
L["Height"] = "Höhe"
L["Color"] = "Farbe"
L["Export as Lua table"] = "Als Lua-Tabelle exportieren"
L["Output the profile as readable Lua code (for use in an addon) instead of a shareable string. This format cannot be re-imported."] =
    "Gibt das Profil als lesbaren Lua-Code aus (zur Verwendung in einem Addon) statt als Teilen-String. Dieses Format kann nicht re-importiert werden."
L["Output the checkpoints as readable Lua code (for use in an addon) instead of a shareable string. This format cannot be re-imported."] =
    "Gibt die Checkpoints als lesbaren Lua-Code aus (zur Verwendung in einem Addon) statt als Teilen-String. Dieses Format kann nicht re-importiert werden."
L["Changelog"] = "Changelog"
L["New"] = "Neu"
L["Updates"] = "Updates"
L["Fixes"] = "Fehlerbehebungen"
L["Show changelog after updates"] = "Changelog nach Updates anzeigen"
L["Reset window size"] = "Fenstergröße zurücksetzen"
L["Welcome to MAUI M+ Timer!"] = "Willkommen bei MAUI M+ Timer!"
L["This quick setup gets you started: pick a starting profile and load the recommended checkpoint targets. Everything can be changed later in the options."] =
    "Dieses kurze Setup hilft beim Start: Wähle ein Startprofil und lade die empfohlenen Checkpoint-Ziele. Alles lässt sich später in den Optionen ändern."
L["Choose a profile"] = "Profil auswählen"
L["Pick a starting look - every element (fonts, colors, bars, modules) can be fine-tuned later in the options."] =
    "Wähle einen Start-Look – jedes Element (Schriften, Farben, Balken, Module) lässt sich später in den Optionen anpassen."
L["Use this profile"] = "Dieses Profil verwenden"
L["Profile applied: %s"] = "Profil angewendet: %s"
L["The classic MAUI look with all default settings."] = "Der klassische MAUI-Look mit allen Standardeinstellungen."
L["The author's personal MAUI look."] = "Der persönliche MAUI-Look des Autors."
L["Back"] = "Zurück"
L["Next"] = "Weiter"
L["Skip"] = "Überspringen"
L["Finish"] = "Fertigstellen"
L["Setup complete! Open the options anytime with /mauimpt."] = "Setup abgeschlossen! Öffne die Optionen jederzeit mit /mauimpt."
L["Automatically open the changelog once after the addon has been updated to a new version."] =
    "Öffnet das Changelog automatisch einmalig, nachdem das Addon auf eine neue Version aktualisiert wurde."
L["Minimap button"] = "Minimap-Button"
L["Show the minimap button."] = "Minimap-Button anzeigen."
L["Left-click"] = "Linksklick"
L["Right-click"] = "Rechtsklick"
L["Options"] = "Optionen"
L["Appearance"] = "Darstellung"
L["Font"] = "Schriftart"
L["Font size"] = "Schriftgröße"
L["Outline"] = "Umrandung"
L["None"] = "Keine"
L["Thick outline"] = "Dicke Umrandung"
L["Text color"] = "Textfarbe"
L["Bars"] = "Balken"
L["Bar texture"] = "Balken-Textur"
L["Bar color"] = "Balkenfarbe"
L["Background color"] = "Hintergrundfarbe"
L["Border color"] = "Rahmenfarbe"
L["Border size"] = "Rahmenstärke"
L["Border"] = "Rahmen"
L["Border offset"] = "Rahmen-Versatz"
L["Show border"] = "Rahmen anzeigen"
L["Border texture"] = "Rahmen-Textur"
L["Background"] = "Hintergrund"
L["Show background"] = "Hintergrund anzeigen"
L["Element order"] = "Element-Anordnung"
L["Assign each element to a row (top to bottom). A row can hold two blocks side by side (left/right); cleared modules re-appear on the lowest free row. Enabled separator lines are placed here as well."] =
    "Weise jedes Element einer Zeile zu (von oben nach unten). Eine Zeile kann zwei Blöcke nebeneinander aufnehmen (links/rechts); entfernte Module erscheinen automatisch in der untersten freien Zeile. Aktivierte Trennlinien werden ebenfalls hier platziert."
L["Reverse bar direction"] = "Balken-Richtung umkehren"
L["Timer sections"] = "Timer-Abschnitte"
L["Over time"] = "Überzeit"
L["Section divider color"] = "Trennlinien-Farbe"
L["Global font"] = "Globale Schrift"
L["Base font for all elements. Each module can override it."] =
    "Basis-Schrift für alle Elemente. Jedes Modul kann sie überschreiben."
L["Pick a font, then click Apply to overwrite the font of every element."] =
    "Schrift wählen, dann auf Übernehmen klicken, um die Schrift aller Elemente zu überschreiben."
L["Apply to all elements"] = "Auf alle Elemente übernehmen"
L["Choose which properties are overwritten on every element."] =
    "Wähle, welche Eigenschaften auf allen Elementen überschrieben werden."
L["This overwrites the font of every element with the global font. Continue?"] =
    "Dies überschreibt die Schrift aller Elemente mit der globalen Schrift. Fortfahren?"
L["This overwrites the selected font properties of every element. Continue?"] =
    "Dies überschreibt die ausgewählten Schrift-Eigenschaften aller Elemente. Fortfahren?"
L["X offset"] = "X-Versatz"
L["Y offset"] = "Y-Versatz"
L["Bar"] = "Balken"
L["Bar width"] = "Balken-Breite"
L["Bar height"] = "Balken-Höhe"
L["0 = use the display width."] = "0 = Anzeigebreite verwenden."
L["Time text"] = "Zeit-Text"
L["Text"] = "Text"
L["Dividers"] = "Trennlinien"
L["Divider color"] = "Trennlinien-Farbe"
L["Divider width"] = "Trennlinien-Breite"
L["Section colors"] = "Abschnittsfarben"
L["Countdown label"] = "Countdown-Text"
L["Vertical position"] = "Vertikale Position"
L["Above"] = "Oben"
L["Below"] = "Unten"
L["Side of divider"] = "Seite der Trennlinie"
L["Position"] = "Position"
L["Left of divider"] = "Links von der Trennlinie"
L["Right of divider"] = "Rechts von der Trennlinie"
L["In bar, left of divider"] = "Im Balken, links von der Trennlinie"
L["In bar, right of divider"] = "Im Balken, rechts von der Trennlinie"
L["Split bar into three"] = "Balken in drei teilen"
L["Split bar at checkpoints"] = "Balken an Checkpoints teilen"
L["Split the bar into segments at each checkpoint (the 100% target is ignored)."] =
    "Teilt den Balken an jedem Checkpoint in Segmente (das 100%-Ziel wird ignoriert)."
L["Segment gap"] = "Segment-Abstand"
L["Segment countdown"] = "Segment-Countdown"
L["Segment percentage"] = "Segment-Prozent"
L["Show the still-needed percentage on each segment; it counts down and hides when the checkpoint is reached."] =
    "Zeigt auf jedem Segment die noch benötigten Prozent; sie zählen runter und werden beim Erreichen des Checkpoints ausgeblendet."
L["Bar-text spacing"] = "Abstand Balken–Text"
L["Vertical space between the time text and the bar."] =
    "Vertikaler Abstand zwischen Zeit-Text und Balken."
L["Show three segments (+3 large, +2 and +1 small) instead of one bar."] =
    "Drei Segmente anzeigen (+3 groß, +2 und +1 klein) statt einem Balken."
L["Colors"] = "Farben"
L["All element colors, grouped by area."] = "Alle Elementfarben, nach Bereichen gruppiert."
L["All section countdowns"] = "Alle Abschnitts-Countdowns"
L["Show a countdown to every section threshold (+3/+2/+1) at once, not just the next."] =
    "Zeigt einen Countdown zu jeder Abschnitts-Schwelle (+3/+2/+1) gleichzeitig, nicht nur zur nächsten."
L["Show keystone level"] = "Schlüsselstufe anzeigen"
L["Show the keystone level next to the dungeon name."] =
    "Zeigt die Schlüsselstein-Stufe neben dem Dungeon-Namen."
L["Level position"] = "Stufen-Position"
L["Color by level rarity"] = "Nach Stufen-Wertung färben"
L["Color the keystone level with Blizzard's rarity color."] =
    "Färbt die Schlüsselstufe mit Blizzards Wertungsfarbe."
L["Separator line"] = "Trennlinie"
L["Show a separator between the dungeon name and the level."] =
    "Zeigt eine Trennlinie zwischen Dungeon-Namen und Stufe."
L["Top left"] = "Oben links"
L["Top right"] = "Oben rechts"
L["Bottom left"] = "Unten links"
L["Bottom right"] = "Unten rechts"
L["Alignment"] = "Ausrichtung"
L["Default text alignment (each module can override this)."] =
    "Standard-Textausrichtung (jedes Modul kann sie überschreiben)."
L["Text alignment for this element."] = "Textausrichtung für dieses Element."
L["Inherit"] = "Erben"
L["Left"] = "Links"
L["Center"] = "Mitte"
L["Right"] = "Rechts"
L["Timer"] = "Timer"
L["Enable"] = "Aktivieren"
L["Toggle demo"] = "Demo umschalten"
L["Section countdown"] = "Abschnitts-Countdown"
L["Show the remaining time until the current +3/+2 threshold on its marker."] =
    "Zeigt die verbleibende Zeit bis zur aktuellen +3/+2-Schwelle am Marker an."
L["Enemy Forces"] = "Streitkräfte"
L["Objectives"] = "Ziele"
L["Deaths"] = "Tode"
L["Splits"] = "Zwischenzeiten"
L["Storage mode"] = "Speichermodus"
L["Keep only the best time per dungeon/level, or a full history."] =
    "Nur die beste Zeit pro Dungeon/Stufe behalten, oder den kompletten Verlauf."
L["Best time only"] = "Nur Bestzeit"
L["Full history"] = "Kompletter Verlauf"
L["Manage times"] = "Zeiten verwalten"
L["Best"] = "Beste"
L["Boss"] = "Boss"
L["No data"] = "Keine Daten"
L["Delete this level"] = "Diese Stufe löschen"
L["Delete dungeon"] = "Dungeon löschen"
L["Removes all stored times for this dungeon (every key level). Cannot be undone."] = "Löscht alle gespeicherten Zeiten dieses Dungeons (jede Stufe). Kann nicht rückgängig gemacht werden."
L["Removes only this run."] = "Löscht nur diesen einen Run."
L["Run vs best"] = "Lauf vs Bestzeit"
L["Checkpoints"] = "Checkpoints"
L["Time"] = "Zeit"
L["Edit checkpoints"] = "Checkpoints bearbeiten"
L["Dungeon"] = "Dungeon"
L["Dungeon name"] = "Dungeon-Name"
L["Affixes"] = "Affixe"
L["Show affixes"] = "Affixe anzeigen"
L["Checkpoint markers"] = "Checkpoint-Marker"
L["Show checkpoint markers"] = "Checkpoint-Marker anzeigen"
L["Mark the checkpoint target percentages on the bar."] =
    "Markiert die Soll-Prozentwerte der Checkpoints auf der Leiste."
L["Marker color"] = "Marker-Farbe"
L["Sample dungeon"] = "Beispiel-Dungeon"
L["Sample affixes"] = "Tyrannisch, Verstärkt"
L["Select a dungeon."] = "Dungeon auswählen."
L["Boss section targets"] = "Soll-% je Boss-Abschnitt"
L["Target %"] = "Soll-%"
L["Remove"] = "Entfernen"
L["Add boss target"] = "Boss-Ziel hinzufügen"
L["Point of No Return"] = "Point of No Return"
L["PoNR"] = "PoNR"
L["Minimum %"] = "Mindest-%"
L["Add point of no return"] = "Point of No Return hinzufügen"
L["Click Export to generate a shareable string of all your checkpoints, then copy it."] = "Klicke auf Export, um einen teilbaren Code aller Checkpoints zu erzeugen, und kopiere ihn."
L["Paste a string and accept to import checkpoints."] = "Code einfügen und bestätigen, um Checkpoints zu importieren."
L["Import checkpoints? Matching dungeons will be overwritten."] = "Checkpoints importieren? Vorhandene Dungeons werden überschrieben."
L["Imported checkpoints for %d dungeon(s)."] = "Checkpoints für %d Dungeon(s) importiert."
L["Load default checkpoints"] = "Standard-Checkpoints laden"
L["Load the author's curated checkpoint targets. Matching dungeons will be overwritten."] =
    "Lädt die vom Autor vorgegebenen Checkpoint-Ziele. Vorhandene Dungeons werden überschrieben."
L["Overwrite matching dungeons with the built-in checkpoints?"] = "Vorhandene Dungeons mit den eingebauten Checkpoints überschreiben?"
L["Sound"] = "Sound"
L["Death"] = "Tod"
L["Forces complete"] = "Streitkräfte 100%"
L["Time expired"] = "Zeit abgelaufen"
L["Run completed"] = "Lauf abgeschlossen"
L["Checkpoint reached"] = "Checkpoint erreicht"
L["Heroism active"] = "Heldentum aktiv"
L["Heroism"] = "Heldentum"
L["Cooldowns"] = "Abklingzeiten"
L["Battle resurrections"] = "Kampf-Wiederbelebungen"
L["Show available battle resurrections and the recharge timer."] =
    "Verfügbare Kampf-Wiederbelebungen und den Aufladungs-Timer anzeigen."
L["Heroism availability"] = "Heldentum-Verfügbarkeit"
L["Show when Heroism/Bloodlust is available again."] =
    "Anzeigen, wann Heldentum/Kampfrausch wieder verfügbar ist."
L["Time position"] = "Position der Zeit"
L["Where the boss split time is shown relative to the name."] =
    "Wo die Boss-Zwischenzeit relativ zum Namen angezeigt wird."
L["Automatic (follow alignment)"] = "Automatisch (nach Ausrichtung)"
L["Left of name"] = "Links vom Namen"
L["Right of name"] = "Rechts vom Namen"
-- Objectives: Bossnamen kürzen
L["Shorten boss names"] = "Bossnamen kürzen"
L["How boss names are shortened for display; internally the full name is always kept."] =
    "Wie Bossnamen für die Anzeige gekürzt werden; intern bleibt immer der volle Name erhalten."
L["Off"] = "Aus"
L["Truncate with ellipsis"] = "Abschneiden (\226\128\166)"
L["First word only"] = "Nur erstes Wort"
L["Abbreviate following words"] = "Folgewörter abkürzen"
L["Max characters"] = "Max. Zeichen"
L["Names longer than this are cut and end with an ellipsis."] =
    "Längere Namen werden abgeschnitten und enden mit \226\128\166"
