-- Localization/enUS.lua
-- Default locale. isDefault = true makes each key map to itself as the fallback
-- value; silent = true (4th arg) suppresses the strict "Missing entry" error so
-- a not-yet-translated key renders as the key itself instead of crashing.

local ADDON_NAME = ...
local L = LibStub("AceLocale-3.0"):NewLocale(ADDON_NAME, "enUS", true, true)
if not L then return end

L["General"] = true
L["Modules"] = true
L["Enable, disable and configure each display element."] = true
L["HUD panel"] = true
-- Settings restructure (groups, About page, best-time bracket)
L["Settings"] = true
L["Other"] = true
L["Fonts"] = true
L["Symbols"] = true
L["Best times"] = true
L["Keystone level"] = true
L["Best time bracket"] = true
L["About"] = true
L["Version"] = true
L["Author"] = true
L["Commands"] = true
L["License"] = true
L["Category"] = true
L["Command list"] = "/mauimpt \226\128\148 open the options\n/mauimpt demo \226\128\148 toggle demo mode\n/mauimpt splits \226\128\148 open the times manager\n/mauimpt checkpoints \226\128\148 open the checkpoint editor\n/mauimpt changelog \226\128\148 open the changelog\n/mauimpt setup \226\128\148 run the setup wizard\n/mauimpt profiles \226\128\148 open the profiles page"
L["No bracket"] = true
L["Credits"] = true
L["Icon credit"] = "Icons: Google Material Symbols (Apache License 2.0)"
L["Sound credit"] = "Sounds: Sophia Conçeição, Universfield, freesound_community, Game Studio, juniorsoundays, Hanifi Şahin, Del, AlesiaDavina, Edimar Filho — from Pixabay (Pixabay Content License)"
L["Bar background color"] = true
L["Fill direction"] = true
L["Row spacing"] = true
L["Extra vertical space between objective rows."] = true
L["Show best times"] = true
L["Show the stored best run's split times behind each element during a run."] = true
L["Best time"] = true
L["Best time size"] = true
L["Best time bracket (left)"] = true
L["Best time bracket (right)"] = true
L["Character(s) shown before a best time. Leave empty for none."] = true
L["Character(s) shown after a best time. Leave empty for none."] = true
L["Left to right"] = true
L["Right to left"] = true
L["Comparison (+/-)"] = true
L["Ahead of best"] = true
L["Behind best"] = true
L["Max time color"] = true
L["Show remaining count"] = true
L["Show the remaining absolute mob count next to the percentage."] = true
L["Defeated boss name"] = true
L["Pending boss name"] = true
L["Split time"] = true
L["Time penalty color"] = true
L["Cooldown color"] = true
L["Recharge color"] = true
L["Remaining count color"] = true
L["Show defeated icon"] = true
L["Show pending icon"] = true
L["Defeated icon"] = true
L["Pending icon"] = true
L["Death icon"] = true
L["Heroism ready icon"] = true
L["Defeated icon color"] = true
L["Pending icon color"] = true
L["Death icon color"] = true
L["Heroism ready icon color"] = true
L["Default"] = true
L["Automation"] = true
L["Auto-hide objective tracker"] = true
L["Hide Blizzard's objective tracker while a Mythic+ run is active."] = true
L["Auto-slot keystone"] = true
L["Automatically place your keystone when the Font of Power is opened."] = true
L["Dungeon icon"] = true
L["Show dungeon icon"] = true
L["Icon position"] = true
L["Icon size"] = true
L["Import / Export"] = true
L["Export"] = true
L["Import"] = true
L["Export string"] = true
L["Click Export to generate a shareable string of your current profile, then copy it."] = true
L["Paste a string and accept to import the profile. It is created under its exported name; your current profile is kept."] = true
L["Profile '%s' already exists. Overwrite it?"] = true
L["Imported profile '%s'."] = true
L["Import failed: %s"] = true
L["Debug mode"] = true
L["Show debug messages in chat."] = true
L["Demo mode"] = true
L["Show sample data so the display can be positioned and styled."] = true
L["Lock display"] = true
L["Prevent the display from being dragged."] = true
L["Width"] = true
L["Width of the display in pixels (increase if text is cut off)."] = true
L["Element spacing"] = true
L["Vertical gap between the stacked HUD elements (e.g. between the timer and forces bars)."] = true
L["Separator lines"] = true
L["Height"] = true
L["Color"] = true
L["Export as Lua table"] = true
L["Output the profile as readable Lua code (for use in an addon) instead of a shareable string. This format cannot be re-imported."] = true
L["Output the checkpoints as readable Lua code (for use in an addon) instead of a shareable string. This format cannot be re-imported."] = true
L["Changelog"] = true
L["New"] = true
L["Updates"] = true
L["Fixes"] = true
L["Show changelog after updates"] = true
L["Reset window size"] = true
L["Welcome to MAUI M+ Timer!"] = true
L["This quick setup gets you started: pick a starting profile and load the recommended checkpoint targets. Everything can be changed later in the options."] = true
L["Choose a profile"] = true
L["Pick a starting look - every element (fonts, colors, bars, modules) can be fine-tuned later in the options."] = true
L["Use this profile"] = true
L["Profile applied: %s"] = true
L["The classic MAUI look with all default settings."] = true
L["The author's personal MAUI look."] = true
L["Requires the !mMT_MediaPack addon for its fonts; without it the default font is used."] = true
L["Back"] = true
L["Next"] = true
L["Skip"] = true
L["Finish"] = true
L["Setup complete! Open the options anytime with /mauimpt."] = true
L["Run setup wizard"] = true
L["Steps"] = true
L["Reopen the first-start setup wizard to pick a profile and load the recommended checkpoint targets."] = true
L["Automatically open the changelog once after the addon has been updated to a new version."] = true
L["Minimap button"] = true
L["Show the minimap button."] = true
L["Left-click"] = true
L["Right-click"] = true
L["Options"] = true
L["Appearance"] = true
L["Font"] = true
L["Font size"] = true
L["Outline"] = true
L["None"] = true
L["Thick outline"] = true
L["Text color"] = true
L["Bars"] = true
L["Bar texture"] = true
L["Bar color"] = true
L["Background color"] = true
L["Border color"] = true
L["Border size"] = true
L["Border"] = true
L["Border offset"] = true
L["Show border"] = true
L["Border texture"] = true
L["Background"] = true
L["Show background"] = true
L["Element order"] = true
L["Assign each element to a row (top to bottom). A row can hold two blocks side by side (left/right); cleared modules re-appear on the lowest free row. Enabled separator lines are placed here as well."] = true
L["Reset order"] = true
L["Reset the element order to the default layout?"] = true
L["Icon instead of label"] = true
L["Replace the 'Run vs best' text with a compact icon."] = true
L["Icons instead of labels"] = true
L["Replace the 'Boss' and 'PoNR' texts with compact icons."] = true
L["Icon color"] = true
L["Boss icon color"] = true
L["PoNR icon color"] = true
L["In bar, centered"] = true
L["In bar, left"] = true
L["In bar, right"] = true
L["Reverse bar direction"] = true
L["Timer sections"] = true
L["Over time"] = true
L["Section divider color"] = true
L["Global font"] = true
L["Base font for all elements. Each module can override it."] = true
L["Pick a font, then click Apply to overwrite the font of every element."] = true
L["Apply to all elements"] = true
L["Choose which properties are overwritten on every element."] = true
L["This overwrites the font of every element with the global font. Continue?"] = true
L["This overwrites the selected font properties of every element. Continue?"] = true
L["X offset"] = true
L["Y offset"] = true
L["Bar"] = true
L["Bar width"] = true
L["Bar height"] = true
L["0 = use the display width."] = true
L["Time text"] = true
L["Text"] = true
L["Dividers"] = true
L["Divider color"] = true
L["Divider width"] = true
L["Section colors"] = true
L["Countdown label"] = true
L["Vertical position"] = true
L["Above"] = true
L["Below"] = true
L["Side of divider"] = true
L["Position"] = true
L["Left of divider"] = true
L["Right of divider"] = true
L["In bar, left of divider"] = true
L["In bar, right of divider"] = true
L["Split bar into three"] = true
L["Split bar at checkpoints"] = true
L["Split the bar into segments at each checkpoint (the 100% target is ignored)."] = true
L["Segment gap"] = true
L["Segment countdown"] = true
L["Segment percentage"] = true
L["Show the still-needed percentage on each segment (split bar) or at each checkpoint marker; it counts down and hides when the checkpoint is reached."] = true
L["All checkpoint countdowns"] = true
L["Show Enemy Forces row"] = true
L["Show percentage text"] = true
L["Show the forces percentage (and remaining count) text on the bar."] = true
L["Add an Enemy Forces entry at the end of the list: live percentage while in progress, completion time once done."] = true
L["Show a countdown to every checkpoint at once, not just the next."] = true
L["Bar-text spacing"] = true
L["Vertical space between the time text and the bar."] = true
L["Show three segments (+3 large, +2 and +1 small) instead of one bar."] = true
L["Colors"] = true
L["All element colors, grouped by area."] = true
L["All section countdowns"] = true
L["Show a countdown to every section threshold (+3/+2/+1) at once, not just the next."] = true
L["Show keystone level"] = true
L["Show the keystone level next to the dungeon name."] = true
L["Level position"] = true
L["Color by level rarity"] = true
L["Color the keystone level with Blizzard's rarity color."] = true
L["Separator line"] = true
L["Show a separator between the dungeon name and the level."] = true
L["Top left"] = true
L["Top right"] = true
L["Bottom left"] = true
L["Bottom right"] = true
L["Alignment"] = true
L["Default text alignment (each module can override this)."] = true
L["Text alignment for this element."] = true
L["Inherit"] = true
L["Left"] = true
L["Center"] = true
L["Right"] = true
L["Timer"] = true
L["Enable"] = true
L["Toggle demo"] = true
L["Section countdown"] = true
L["Show the remaining time until the current +3/+2 threshold on its marker."] = true
L["Enemy Forces"] = true
L["Objectives"] = true
L["Deaths"] = true
L["Splits"] = true
L["Storage mode"] = true
L["Keep only the best time per dungeon/level, or a full history."] = true
L["Best time only"] = true
L["Full history"] = true
L["Manage times"] = true
L["Best"] = true
L["Boss"] = true
L["No data"] = true
L["Delete this level"] = true
L["Delete dungeon"] = true
L["Removes all stored times for this dungeon (every key level). Cannot be undone."] = true
L["Removes only this run."] = true
L["Run vs best"] = true
L["Checkpoints"] = true
L["Time"] = true
L["Edit checkpoints"] = true
L["Dungeon"] = true
L["Dungeon name"] = true
L["Affixes"] = true
L["Show affixes"] = true
L["Checkpoint markers"] = true
L["Show checkpoint markers"] = true
L["Mark the checkpoint target percentages on the bar."] = true
L["Marker color"] = true
L["Sample dungeon"] = "Sample Dungeon"
L["Sample affixes"] = "Tyrannical, Fortified"
L["Select a dungeon."] = true
L["Boss section targets"] = true
L["Target %"] = true
L["Remove"] = true
L["Add boss target"] = true
L["Point of No Return"] = true
L["PoNR"] = true
L["Minimum %"] = true
L["Add point of no return"] = true
L["Click Export to generate a shareable string of all your checkpoints, then copy it."] = true
L["Paste a string and accept to import checkpoints."] = true
L["Import checkpoints? Matching dungeons will be overwritten."] = true
L["Imported checkpoints for %d dungeon(s)."] = true
L["Load default checkpoints"] = true
L["Load the author's curated checkpoint targets. Matching dungeons will be overwritten."] = true
L["Overwrite matching dungeons with the built-in checkpoints?"] = true
L["Sound"] = true
L["Death"] = true
L["Forces complete"] = true
L["Time expired"] = true
L["Run completed"] = true
L["Checkpoint reached"] = true
L["Heroism active"] = true
L["Heroism"] = true
L["Cooldowns"] = true
L["Battle resurrections"] = true
L["Show available battle resurrections and the recharge timer."] = true
L["Heroism availability"] = true
L["Show when Heroism/Bloodlust is available again."] = true
L["Time position"] = true
L["Where the boss split time is shown relative to the name."] = true
L["Automatic (follow alignment)"] = true
L["Left of name"] = true
L["Right of name"] = true
-- Objectives: boss-name shortening
L["Shorten boss names"] = true
L["How boss names are shortened for display; internally the full name is always kept."] = true
L["Off"] = true
L["Truncate with ellipsis"] = "Truncate (\226\128\166)"
L["First word only"] = true
L["Abbreviate following words"] = true
L["Max characters"] = true
L["Names longer than this are cut and end with an ellipsis."] = true
