-- Localization/zhCN.lua
-- Simplified Chinese locale. Only overrides; missing keys fall back to enUS.
-- Game-specific terms follow Blizzard's official zhCN client terminology.

local ADDON_NAME = ...
local L = LibStub("AceLocale-3.0"):NewLocale(ADDON_NAME, "zhCN")
if not L then return end

L["General"] = "常规"
L["Modules"] = "模块"
L["Enable, disable and configure each display element."] = "启用、禁用并配置每个显示元素。"
L["HUD panel"] = "HUD 面板"
-- Settings restructure (groups, About page, best-time bracket)
L["Settings"] = "设置"
L["Other"] = "其他"
L["Fonts"] = "字体"
L["Symbols"] = "符号"
L["Best times"] = "最佳时间"
L["Keystone level"] = "钥石等级"
L["Best time bracket"] = "最佳时间括号"
L["About"] = "关于"
L["Version"] = "版本"
L["Author"] = "作者"
L["Commands"] = "命令"
L["License"] = "许可协议"
L["Category"] = "分类"
L["Links"] = "链接"
L["Command list"] = "/mauimpt — 打开选项\n/mauimpt demo — 切换演示模式\n/mauimpt splits — 打开时间管理器\n/mauimpt checkpoints — 打开检查点编辑器\n/mauimpt changelog — 打开更新日志\n/mauimpt setup — 运行设置向导\n/mauimpt profiles — 打开配置文件页面"
L["No bracket"] = "无"
L["Credits"] = "鸣谢"
L["Icon credit"] = "图标：Google Material Symbols (Apache License 2.0)"
L["Sound credit"] = "音效：Sophia Conçeição, Universfield, freesound_community, Game Studio, juniorsoundays, Hanifi Şahin, Del, AlesiaDavina, Edimar Filho — 来自 Pixabay (Pixabay Content License)"
L["Bar background color"] = "进度条背景色"
L["Fill direction"] = "填充方向"
L["Row spacing"] = "行间距"
L["Extra vertical space between objective rows."] = "目标行之间的额外垂直间距。"
L["Show best times"] = "显示最佳时间"
L["Show the stored best run's split times behind each element during a run."] =
    "计时过程中在每个元素后方显示已保存最佳记录的分段时间。"
L["Best time"] = "最佳时间"
L["Best time size"] = "最佳时间大小"
L["Best time bracket (left)"] = "最佳时间括号（左）"
L["Best time bracket (right)"] = "最佳时间括号（右）"
L["Character(s) shown before a best time. Leave empty for none."] = "显示在最佳时间之前的字符。留空则不显示。"
L["Character(s) shown after a best time. Leave empty for none."] = "显示在最佳时间之后的字符。留空则不显示。"
L["Left to right"] = "从左到右"
L["Right to left"] = "从右到左"
L["Comparison (+/-)"] = "对比 (+/-)"
L["Ahead of best"] = "领先最佳"
L["Behind best"] = "落后最佳"
L["Max time color"] = "最大时间颜色"
L["Show remaining count"] = "显示剩余数量"
L["Percentage only"] = "仅显示百分比"
L["Show only the forces percentage in the main text, without the remaining count, best time or completion delta."] =
    "主文本仅显示敌军百分比，不显示剩余数量、最佳时间或完成差值。"
L["Hide first segment countdown"] = "隐藏第一段倒计时"
L["Hide the first segment's countdown label so it cannot overlap the main percentage text."] =
    "隐藏第一段的倒计时标签，使其不会与主百分比文本重叠。"
L["Show the remaining absolute mob count next to the percentage."] = "在百分比旁显示剩余的绝对怪物数量。"
L["Defeated boss name"] = "首领名称（已击败）"
L["Pending boss name"] = "首领名称（待击败）"
L["Split time"] = "分段时间"
L["Time penalty color"] = "时间惩罚颜色"
L["Cooldown color"] = "冷却颜色"
L["Recharge color"] = "充能颜色"
L["Remaining count color"] = "剩余数量颜色"
L["Show defeated icon"] = "显示已击败图标"
L["Show pending icon"] = "显示待击败图标"
L["Defeated icon"] = "图标（已击败）"
L["Pending icon"] = "图标（待击败）"
L["Death icon"] = "死亡图标"
L["Heroism ready icon"] = "英勇就绪图标"
L["Defeated icon color"] = "图标颜色（已击败）"
L["Pending icon color"] = "图标颜色（待击败）"
L["Death icon color"] = "死亡图标颜色"
L["Heroism ready icon color"] = "英勇就绪图标颜色"
L["Default"] = "默认"
L["Automation"] = "自动化"
L["Auto-hide objective tracker"] = "自动隐藏任务追踪器"
L["Hide Blizzard's objective tracker while a Mythic+ run is active."] = "在史诗钥石运行期间隐藏暴雪的任务追踪器。"
L["Auto-slot keystone"] = "自动放入钥石"
L["Automatically place your keystone when the Font of Power is opened."] = "打开力量之源时自动放入你的钥石。"
L["Dungeon icon"] = "地下城图标"
L["Show dungeon icon"] = "显示地下城图标"
L["Icon position"] = "图标位置"
L["Icon size"] = "图标大小"
L["Import / Export"] = "导入 / 导出"
L["Export"] = "导出"
L["Import"] = "导入"
L["Export string"] = "导出字符串"
L["Click Export to generate a shareable string of your current profile, then copy it."] =
    "点击导出以生成当前配置文件的可分享字符串，然后复制它。"
L["Paste a string and accept to import the profile. It is created under its exported name; your current profile is kept."] =
    "粘贴字符串并确认以导入配置文件。它将以其导出名称创建；你当前的配置文件将保留。"
L["Profile '%s' already exists. Overwrite it?"] = "配置文件 '%s' 已存在。是否覆盖？"
L["Imported profile '%s'."] = "已导入配置文件 '%s'。"
L["Import failed: %s"] = "导入失败：%s"
L["Debug mode"] = "调试模式"
L["Show debug messages in chat."] = "在聊天中显示调试信息。"
L["Demo mode"] = "演示模式"
L["Show sample data so the display can be positioned and styled."] = "显示示例数据，以便定位和设置显示样式。"
L["Lock display"] = "锁定显示"
L["Prevent the display from being dragged."] = "防止拖动显示。"
L["Width"] = "宽度"
L["Width of the display in pixels (increase if text is cut off)."] = "显示的宽度（像素）（如果文字被截断请增大）。"
L["Element spacing"] = "元素间距"
L["Vertical gap between the stacked HUD elements (e.g. between the timer and forces bars)."] =
    "堆叠的 HUD 元素之间的垂直间距（例如计时器与敌军进度条之间）。"
L["Separator lines"] = "分隔线"
L["Height"] = "高度"
L["Color"] = "颜色"
L["Export as Lua table"] = "导出为 Lua 表"
L["Output the profile as readable Lua code (for use in an addon) instead of a shareable string. This format cannot be re-imported."] =
    "将配置文件输出为可读的 Lua 代码（用于插件）而非可分享字符串。此格式无法重新导入。"
L["Output the checkpoints as readable Lua code (for use in an addon) instead of a shareable string. This format cannot be re-imported."] =
    "将检查点输出为可读的 Lua 代码（用于插件）而非可分享字符串。此格式无法重新导入。"
L["Changelog"] = "更新日志"
L["New"] = "新增"
L["Updates"] = "更新"
L["Fixes"] = "修复"
L["Show changelog after updates"] = "更新后显示更新日志"
L["Reset window size"] = "重置窗口大小"
L["Welcome to MAUI M+ Timer!"] = "欢迎使用 MAUI M+ Timer！"
L["This quick setup gets you started: pick a starting profile and load the recommended checkpoint targets. Everything can be changed later in the options."] =
    "此快速设置助你上手：选择一个起始配置文件并加载推荐的检查点目标。所有内容之后都可在选项中更改。"
L["Choose a profile"] = "选择配置文件"
L["Pick a starting look - every element (fonts, colors, bars, modules) can be fine-tuned later in the options."] =
    "选择一个起始外观——每个元素（字体、颜色、进度条、模块）之后都可在选项中微调。"
L["Use this profile"] = "使用此配置文件"
L["Profile applied: %s"] = "已应用配置文件：%s"
L["The classic MAUI look with all default settings."] = "经典 MAUI 外观，全部为默认设置。"
L["The author's personal MAUI look."] = "作者个人的 MAUI 外观。"
L["A reduced, minimal look: only dungeon, timer, objectives and deaths (checkpoints, cooldowns and enemy forces off; the run-vs-best line is hidden but still recorded)."] =
    "精简的极简外观：仅显示地下城、计时器、目标和死亡（检查点、冷却和敌军关闭；本次 vs 最佳行隐藏但仍记录）。"
L["A compact full layout with a separator line and a slim enemy-forces bar (forces countdown below the bar)."] =
    "紧凑的完整布局，带分隔线和纤细的敌军进度条（敌军倒计时显示在进度条下方）。"
L["Requires the !mMT_MediaPack addon for its fonts; without it the default font is used."] =
    "需要 !mMT_MediaPack 插件提供字体；未安装时将使用默认字体。"
L["Download media pack"] = "下载媒体包"
L["Copy the link to download the media pack (%s), then open it in your web browser:"] =
    "复制链接以下载媒体包（%s），然后在浏览器中打开："
L["Back"] = "上一步"
L["Next"] = "下一步"
L["Skip"] = "跳过"
L["Finish"] = "完成"
L["Setup complete! Open the options anytime with /mauimpt."] = "设置完成！随时使用 /mauimpt 打开选项。"
L["Run setup wizard"] = "运行设置向导"
L["Steps"] = "步骤"
L["Reopen the first-start setup wizard to pick a profile and load the recommended checkpoint targets."] =
    "重新打开首次启动设置向导，选择配置文件并加载推荐的检查点目标。"
L["Automatically open the changelog once after the addon has been updated to a new version."] =
    "插件更新到新版本后自动打开一次更新日志。"
L["Minimap button"] = "小地图按钮"
L["Show the minimap button."] = "显示小地图按钮。"
L["Left-click"] = "左键点击"
L["Right-click"] = "右键点击"
L["Options"] = "选项"
L["Appearance"] = "外观"
L["Font"] = "字体"
L["Font size"] = "字体大小"
L["Outline"] = "描边"
L["None"] = "无"
L["Thick outline"] = "粗描边"
L["Text color"] = "文字颜色"
L["Bars"] = "进度条"
L["Bar texture"] = "进度条材质"
L["Bar color"] = "进度条颜色"
L["Background color"] = "背景颜色"
L["Border color"] = "边框颜色"
L["Border size"] = "边框大小"
L["Border"] = "边框"
L["Border offset"] = "边框偏移"
L["Show border"] = "显示边框"
L["Border texture"] = "边框材质"
L["Background"] = "背景"
L["Show background"] = "显示背景"
L["Element order"] = "元素顺序"
L["Assign each element to a row (top to bottom). A row can hold two blocks side by side (left/right); cleared modules re-appear on the lowest free row. Enabled separator lines are placed here as well."] =
    "将每个元素分配到某一行（从上到下）。一行可并排容纳两个块（左/右）；被清除的模块会重新出现在最低的空闲行。已启用的分隔线也放置于此。"
L["Reset order"] = "重置顺序"
L["Reset the element order to the default layout?"] = "将元素顺序重置为默认布局？"
L["Icon instead of label"] = "用图标代替标签"
L["Show label"] = "显示标签"
L["Show run vs best line"] = "显示本次 vs 最佳行"
L["Show the run-vs-best line in the HUD. When off, best times are still recorded for the timer, forces and objectives - only this line is hidden. Removing 'Splits' in General -> Element order does the same."] =
    "在 HUD 中显示本次 vs 最佳行。关闭时仍会为计时器、敌军和目标记录最佳时间，仅隐藏此行。在“常规 -> 元素排序”中移除“分段时间”效果相同。"
L["Show the 'Run vs best' label before the delta. When off, only the +/- delta is shown."] =
    "在差值前显示“本次 vs 最佳”标签。关闭时仅显示 +/- 差值。"
L["Replace the 'Run vs best' text with a compact icon."] = "用紧凑图标代替“本次 vs 最佳”文字。"
L["Icons instead of labels"] = "用图标代替标签"
L["Replace the 'Boss' and 'PoNR' texts with compact icons."] = "用紧凑图标代替“首领”和“PoNR”文字。"
L["Icon color"] = "图标颜色"
L["Boss icon color"] = "首领图标颜色"
L["PoNR icon color"] = "PoNR 图标颜色"
L["In bar, centered"] = "进度条内，居中"
L["In bar, left"] = "进度条内，居左"
L["In bar, right"] = "进度条内，居右"
L["Reverse bar direction"] = "反转进度条方向"
L["Timer sections"] = "计时器区段"
L["Over time"] = "超时"
L["Section divider color"] = "区段分隔线颜色"
L["Global font"] = "全局字体"
L["Base font for all elements. Each module can override it."] = "所有元素的基础字体。每个模块都可覆盖它。"
L["Pick a font, then click Apply to overwrite the font of every element."] =
    "选择字体，然后点击应用以覆盖所有元素的字体。"
L["Apply to all elements"] = "应用到所有元素"
L["Choose which properties are overwritten on every element."] = "选择要在所有元素上覆盖的属性。"
L["This overwrites the font of every element with the global font. Continue?"] =
    "这将用全局字体覆盖所有元素的字体。是否继续？"
L["This overwrites the selected font properties of every element. Continue?"] =
    "这将覆盖所有元素所选的字体属性。是否继续？"
L["X offset"] = "X 偏移"
L["Y offset"] = "Y 偏移"
L["Bar"] = "进度条"
L["Bar width"] = "进度条宽度"
L["Bar height"] = "进度条高度"
L["0 = use the display width."] = "0 = 使用显示宽度。"
L["Time text"] = "时间文字"
L["Text"] = "文字"
L["Dividers"] = "分隔线"
L["Divider color"] = "分隔线颜色"
L["Divider width"] = "分隔线宽度"
L["Section colors"] = "区段颜色"
L["Countdown label"] = "倒计时文字"
L["Vertical position"] = "垂直位置"
L["Above"] = "上方"
L["Below"] = "下方"
L["Side of divider"] = "分隔线的一侧"
L["Position"] = "位置"
L["Left of divider"] = "分隔线左侧"
L["Right of divider"] = "分隔线右侧"
L["In bar, left of divider"] = "进度条内，分隔线左侧"
L["In bar, right of divider"] = "进度条内，分隔线右侧"
L["Split bar into three"] = "将进度条分为三段"
L["Timer bar"] = "计时器进度条"
L["Show timer bar"] = "显示计时器进度条"
L["Show the timer bar (with section dividers and countdowns). It is its own block under General -> Element order, so it can be positioned or removed there too."] =
    "显示计时器进度条（含分段分隔线和倒计时）。它在“常规 -> 元素排序”中是独立块，也可在此定位或移除。"
L["Split bar at checkpoints"] = "在检查点分割进度条"
L["Split the bar into segments at each checkpoint (the 100% target is ignored)."] =
    "在每个检查点将进度条分成若干段（忽略 100% 目标）。"
L["Segment gap"] = "分段间隙"
L["Segment countdown"] = "分段倒计时"
L["Segment percentage"] = "分段百分比"
L["Show the still-needed percentage on each segment (split bar) or at each checkpoint marker; it counts down and hides when the checkpoint is reached."] =
    "在每个分段（分割进度条）或每个检查点标记处显示仍需的百分比；它会倒数并在到达检查点时隐藏。"
L["All checkpoint countdowns"] = "所有检查点倒计时"
L["Show Enemy Forces row"] = "显示敌军数量行"
L["Show percentage text"] = "显示百分比文字"
L["Show the forces percentage (and remaining count) text on the bar."] =
    "在进度条上显示敌军百分比（及剩余数量）文字。"
L["Add an Enemy Forces entry at the end of the list: live percentage while in progress, completion time once done."] =
    "在列表末尾添加一个敌军数量条目：进行中显示实时百分比，完成后显示完成时间。"
L["Show a countdown to every checkpoint at once, not just the next."] =
    "同时显示到每个检查点的倒计时，而不仅仅是下一个。"
L["Bar-text spacing"] = "进度条—文字间距"
L["Vertical space between the time text and the bar."] = "时间文字与进度条之间的垂直间距。"
L["Show three segments (+3 large, +2 and +1 small) instead of one bar."] =
    "显示三个分段（+3 大，+2 和 +1 小）而非单个进度条。"
L["Colors"] = "颜色"
L["All element colors, grouped by area."] = "所有元素颜色，按区域分组。"
L["All section countdowns"] = "所有区段倒计时"
L["Show a countdown to every section threshold (+3/+2/+1) at once, not just the next."] =
    "同时显示到每个区段阈值（+3/+2/+1）的倒计时，而不仅仅是下一个。"
L["Show keystone level"] = "显示钥石等级"
L["Show the keystone level next to the dungeon name."] = "在地下城名称旁显示钥石等级。"
L["Level position"] = "等级位置"
L["Color by level rarity"] = "按等级品质着色"
L["Color the keystone level with Blizzard's rarity color."] = "使用暴雪的品质颜色为钥石等级着色。"
L["Separator line"] = "分隔线"
L["Show a separator between the dungeon name and the level."] = "在地下城名称和等级之间显示一条分隔线。"
L["Top left"] = "左上"
L["Top right"] = "右上"
L["Bottom left"] = "左下"
L["Bottom right"] = "右下"
L["Alignment"] = "对齐"
L["Default text alignment (each module can override this)."] = "默认文字对齐方式（每个模块都可覆盖）。"
L["Text alignment for this element."] = "此元素的文字对齐方式。"
L["Inherit"] = "继承"
L["Left"] = "左对齐"
L["Center"] = "居中"
L["Right"] = "右对齐"
L["Timer"] = "计时器"
L["Enable"] = "启用"
L["Toggle demo"] = "切换演示"
L["Section countdown"] = "区段倒计时"
L["Show the remaining time until the current +3/+2 threshold on its marker."] =
    "在标记处显示距当前 +3/+2 阈值的剩余时间。"
L["Enemy Forces"] = "敌军数量"
L["Objectives"] = "目标"
L["Deaths"] = "死亡次数"
L["Splits"] = "分段时间"
L["Storage mode"] = "存储模式"
L["Keep only the best time per dungeon/level, or a full history."] =
    "每个地下城/等级仅保留最佳时间，或保留完整历史。"
L["Best time only"] = "仅最佳时间"
L["Full history"] = "完整历史"
L["Manage times"] = "管理时间"
L["Best"] = "最佳"
L["Boss"] = "首领"
L["No data"] = "无数据"
L["Delete this level"] = "删除此等级"
L["Delete dungeon"] = "删除地下城"
L["Removes all stored times for this dungeon (every key level). Cannot be undone."] =
    "删除此地下城所有已保存的时间（每个钥石等级）。无法撤销。"
L["Removes only this run."] = "仅删除此次记录。"
L["Run vs best"] = "本次 vs 最佳"
L["Checkpoints"] = "检查点"
L["Time"] = "时间"
L["Edit checkpoints"] = "编辑检查点"
L["Dungeon"] = "地下城"
L["Dungeon name"] = "地下城名称"
L["Affixes"] = "词缀"
L["Show affixes"] = "显示词缀"
L["Checkpoint markers"] = "检查点标记"
L["Show checkpoint markers"] = "显示检查点标记"
L["Mark the checkpoint target percentages on the bar."] = "在进度条上标记检查点目标百分比。"
L["Marker color"] = "标记颜色"
L["Sample dungeon"] = "示例地下城"
L["Sample affixes"] = "残暴，强韧"
L["Select a dungeon."] = "选择一个地下城。"
L["Boss section targets"] = "首领区段目标"
L["Target %"] = "目标 %"
L["Remove"] = "移除"
L["Add boss target"] = "添加首领目标"
L["Point of No Return"] = "无法回头点"
L["PoNR"] = "PoNR"
L["Minimum %"] = "最低 %"
L["Add point of no return"] = "添加无法回头点"
L["Click Export to generate a shareable string of all your checkpoints, then copy it."] =
    "点击导出以生成所有检查点的可分享字符串，然后复制它。"
L["Paste a string and accept to import checkpoints."] = "粘贴字符串并确认以导入检查点。"
L["Import checkpoints? Matching dungeons will be overwritten."] = "导入检查点？匹配的地下城将被覆盖。"
L["Imported checkpoints for %d dungeon(s)."] = "已为 %d 个地下城导入检查点。"
L["Load default checkpoints"] = "加载默认检查点"
L["Load the author's curated checkpoint targets. Matching dungeons will be overwritten."] =
    "加载作者精选的检查点目标。匹配的地下城将被覆盖。"
L["Overwrite matching dungeons with the built-in checkpoints?"] = "用内置检查点覆盖匹配的地下城？"
L["Sound"] = "音效"
L["Death"] = "死亡"
L["Forces complete"] = "敌军完成"
L["Time expired"] = "时间耗尽"
L["Run completed"] = "运行完成"
L["Checkpoint reached"] = "到达检查点"
L["Heroism active"] = "英勇激活"
L["Heroism"] = "英勇"
L["Cooldowns"] = "冷却"
L["Battle resurrections"] = "战斗复活"
L["Show available battle resurrections and the recharge timer."] = "显示可用的战斗复活次数及充能计时。"
L["Heroism availability"] = "英勇可用性"
L["Show when Heroism/Bloodlust is available again."] = "显示英勇/嗜血何时再次可用。"
L["Time position"] = "时间位置"
L["Where the boss split time is shown relative to the name."] = "首领分段时间相对于名称的显示位置。"
L["Automatic (follow alignment)"] = "自动（跟随对齐）"
L["Left of name"] = "名称左侧"
L["Right of name"] = "名称右侧"
-- Objectives: boss-name shortening
L["Shorten boss names"] = "缩短首领名称"
L["How boss names are shortened for display; internally the full name is always kept."] =
    "首领名称如何缩短显示；内部始终保留完整名称。"
L["Off"] = "关闭"
L["Truncate with ellipsis"] = "截断（…）"
L["First word only"] = "仅第一个词"
L["Abbreviate following words"] = "缩写后续词语"
L["Max characters"] = "最大字符数"
L["Names longer than this are cut and end with an ellipsis."] = "超过此长度的名称将被截断并以省略号结尾。"
