-- Localization/zhTW.lua
-- Traditional Chinese locale (Taiwan client). Only overrides; missing keys fall back to enUS.
-- Game-specific terms follow Blizzard's official zhTW client terminology.

local ADDON_NAME = ...
local L = LibStub("AceLocale-3.0"):NewLocale(ADDON_NAME, "zhTW")
if not L then return end

L["General"] = "一般"
L["Modules"] = "模組"
L["Enable, disable and configure each display element."] = "啟用、停用並設定每個顯示元素。"
L["HUD panel"] = "HUD 面板"
-- Settings restructure (groups, About page, best-time bracket)
L["Settings"] = "設定"
L["Other"] = "其他"
L["Fonts"] = "字型"
L["Symbols"] = "符號"
L["Best times"] = "最佳時間"
L["Keystone level"] = "鑰石等級"
L["Best time bracket"] = "最佳時間括號"
L["About"] = "關於"
L["Version"] = "版本"
L["Author"] = "作者"
L["Commands"] = "指令"
L["License"] = "授權"
L["Category"] = "分類"
L["Command list"] = "/mauimpt — 開啟選項\n/mauimpt demo — 切換展示模式\n/mauimpt splits — 開啟時間管理器\n/mauimpt checkpoints — 開啟檢查點編輯器\n/mauimpt changelog — 開啟更新日誌\n/mauimpt setup — 執行設定精靈\n/mauimpt profiles — 開啟設定檔頁面"
L["No bracket"] = "無"
L["Credits"] = "致謝"
L["Icon credit"] = "圖示：Google Material Symbols (Apache License 2.0)"
L["Sound credit"] = "音效：Sophia Conçeição, Universfield, freesound_community, Game Studio, juniorsoundays, Hanifi Şahin, Del, AlesiaDavina, Edimar Filho — 來自 Pixabay (Pixabay Content License)"
L["Bar background color"] = "進度條背景色"
L["Fill direction"] = "填充方向"
L["Row spacing"] = "行間距"
L["Extra vertical space between objective rows."] = "目標行之間的額外垂直間距。"
L["Show best times"] = "顯示最佳時間"
L["Show the stored best run's split times behind each element during a run."] =
    "計時過程中在每個元素後方顯示已儲存最佳紀錄的分段時間。"
L["Best time"] = "最佳時間"
L["Best time size"] = "最佳時間大小"
L["Best time bracket (left)"] = "最佳時間括號（左）"
L["Best time bracket (right)"] = "最佳時間括號（右）"
L["Character(s) shown before a best time. Leave empty for none."] = "顯示在最佳時間之前的字元。留空則不顯示。"
L["Character(s) shown after a best time. Leave empty for none."] = "顯示在最佳時間之後的字元。留空則不顯示。"
L["Left to right"] = "由左至右"
L["Right to left"] = "由右至左"
L["Comparison (+/-)"] = "比較 (+/-)"
L["Ahead of best"] = "領先最佳"
L["Behind best"] = "落後最佳"
L["Max time color"] = "最大時間顏色"
L["Show remaining count"] = "顯示剩餘數量"
L["Show the remaining absolute mob count next to the percentage."] = "在百分比旁顯示剩餘的絕對怪物數量。"
L["Defeated boss name"] = "首領名稱（已擊敗）"
L["Pending boss name"] = "首領名稱（待擊敗）"
L["Split time"] = "分段時間"
L["Time penalty color"] = "時間懲罰顏色"
L["Cooldown color"] = "冷卻顏色"
L["Recharge color"] = "充能顏色"
L["Remaining count color"] = "剩餘數量顏色"
L["Show defeated icon"] = "顯示已擊敗圖示"
L["Show pending icon"] = "顯示待擊敗圖示"
L["Defeated icon"] = "圖示（已擊敗）"
L["Pending icon"] = "圖示（待擊敗）"
L["Death icon"] = "死亡圖示"
L["Heroism ready icon"] = "英勇就緒圖示"
L["Defeated icon color"] = "圖示顏色（已擊敗）"
L["Pending icon color"] = "圖示顏色（待擊敗）"
L["Death icon color"] = "死亡圖示顏色"
L["Heroism ready icon color"] = "英勇就緒圖示顏色"
L["Default"] = "預設"
L["Automation"] = "自動化"
L["Auto-hide objective tracker"] = "自動隱藏任務追蹤器"
L["Hide Blizzard's objective tracker while a Mythic+ run is active."] = "在傳奇鑰石進行期間隱藏暴雪的任務追蹤器。"
L["Auto-slot keystone"] = "自動放入鑰石"
L["Automatically place your keystone when the Font of Power is opened."] = "開啟力量之源時自動放入你的鑰石。"
L["Dungeon icon"] = "地城圖示"
L["Show dungeon icon"] = "顯示地城圖示"
L["Icon position"] = "圖示位置"
L["Icon size"] = "圖示大小"
L["Import / Export"] = "匯入 / 匯出"
L["Export"] = "匯出"
L["Import"] = "匯入"
L["Export string"] = "匯出字串"
L["Click Export to generate a shareable string of your current profile, then copy it."] =
    "點擊匯出以產生目前設定檔的可分享字串，然後複製它。"
L["Paste a string and accept to import the profile. It is created under its exported name; your current profile is kept."] =
    "貼上字串並確認以匯入設定檔。它將以其匯出名稱建立；你目前的設定檔將保留。"
L["Profile '%s' already exists. Overwrite it?"] = "設定檔 '%s' 已存在。是否覆寫？"
L["Imported profile '%s'."] = "已匯入設定檔 '%s'。"
L["Import failed: %s"] = "匯入失敗：%s"
L["Debug mode"] = "除錯模式"
L["Show debug messages in chat."] = "在聊天中顯示除錯訊息。"
L["Demo mode"] = "展示模式"
L["Show sample data so the display can be positioned and styled."] = "顯示範例資料，以便定位並設定顯示樣式。"
L["Lock display"] = "鎖定顯示"
L["Prevent the display from being dragged."] = "防止拖曳顯示。"
L["Width"] = "寬度"
L["Width of the display in pixels (increase if text is cut off)."] = "顯示的寬度（像素）（如果文字被截斷請增大）。"
L["Element spacing"] = "元素間距"
L["Vertical gap between the stacked HUD elements (e.g. between the timer and forces bars)."] =
    "堆疊的 HUD 元素之間的垂直間距（例如計時器與敵軍進度條之間）。"
L["Separator lines"] = "分隔線"
L["Height"] = "高度"
L["Color"] = "顏色"
L["Export as Lua table"] = "匯出為 Lua 表格"
L["Output the profile as readable Lua code (for use in an addon) instead of a shareable string. This format cannot be re-imported."] =
    "將設定檔輸出為可讀的 Lua 程式碼（用於插件）而非可分享字串。此格式無法重新匯入。"
L["Output the checkpoints as readable Lua code (for use in an addon) instead of a shareable string. This format cannot be re-imported."] =
    "將檢查點輸出為可讀的 Lua 程式碼（用於插件）而非可分享字串。此格式無法重新匯入。"
L["Changelog"] = "更新日誌"
L["New"] = "新增"
L["Updates"] = "更新"
L["Fixes"] = "修正"
L["Show changelog after updates"] = "更新後顯示更新日誌"
L["Reset window size"] = "重設視窗大小"
L["Welcome to MAUI M+ Timer!"] = "歡迎使用 MAUI M+ Timer！"
L["This quick setup gets you started: pick a starting profile and load the recommended checkpoint targets. Everything can be changed later in the options."] =
    "此快速設定助你上手：選擇一個起始設定檔並載入建議的檢查點目標。所有內容之後都可在選項中變更。"
L["Choose a profile"] = "選擇設定檔"
L["Pick a starting look - every element (fonts, colors, bars, modules) can be fine-tuned later in the options."] =
    "選擇一個起始外觀——每個元素（字型、顏色、進度條、模組）之後都可在選項中微調。"
L["Use this profile"] = "使用此設定檔"
L["Profile applied: %s"] = "已套用設定檔：%s"
L["The classic MAUI look with all default settings."] = "經典 MAUI 外觀，全部為預設設定。"
L["The author's personal MAUI look."] = "作者個人的 MAUI 外觀。"
L["Back"] = "上一步"
L["Next"] = "下一步"
L["Skip"] = "略過"
L["Finish"] = "完成"
L["Setup complete! Open the options anytime with /mauimpt."] = "設定完成！隨時使用 /mauimpt 開啟選項。"
L["Automatically open the changelog once after the addon has been updated to a new version."] =
    "插件更新至新版本後自動開啟一次更新日誌。"
L["Minimap button"] = "小地圖按鈕"
L["Show the minimap button."] = "顯示小地圖按鈕。"
L["Left-click"] = "左鍵點擊"
L["Right-click"] = "右鍵點擊"
L["Options"] = "選項"
L["Appearance"] = "外觀"
L["Font"] = "字型"
L["Font size"] = "字型大小"
L["Outline"] = "外框"
L["None"] = "無"
L["Thick outline"] = "粗外框"
L["Text color"] = "文字顏色"
L["Bars"] = "進度條"
L["Bar texture"] = "進度條材質"
L["Bar color"] = "進度條顏色"
L["Background color"] = "背景顏色"
L["Border color"] = "邊框顏色"
L["Border size"] = "邊框大小"
L["Border"] = "邊框"
L["Border offset"] = "邊框偏移"
L["Show border"] = "顯示邊框"
L["Border texture"] = "邊框材質"
L["Background"] = "背景"
L["Show background"] = "顯示背景"
L["Element order"] = "元素順序"
L["Assign each element to a row (top to bottom). A row can hold two blocks side by side (left/right); cleared modules re-appear on the lowest free row. Enabled separator lines are placed here as well."] =
    "將每個元素指派到某一行（從上到下）。一行可並排容納兩個區塊（左/右）；被清除的模組會重新出現在最低的空閒行。已啟用的分隔線也放置於此。"
L["Reset order"] = "重設順序"
L["Reset the element order to the default layout?"] = "將元素順序重設為預設版面配置？"
L["Icon instead of label"] = "以圖示代替標籤"
L["Replace the 'Run vs best' text with a compact icon."] = "以精簡圖示代替「本次 vs 最佳」文字。"
L["Icons instead of labels"] = "以圖示代替標籤"
L["Replace the 'Boss' and 'PoNR' texts with compact icons."] = "以精簡圖示代替「首領」和「PoNR」文字。"
L["Icon color"] = "圖示顏色"
L["Boss icon color"] = "首領圖示顏色"
L["PoNR icon color"] = "PoNR 圖示顏色"
L["In bar, centered"] = "進度條內，置中"
L["In bar, left"] = "進度條內，靠左"
L["In bar, right"] = "進度條內，靠右"
L["Reverse bar direction"] = "反轉進度條方向"
L["Timer sections"] = "計時器區段"
L["Over time"] = "超時"
L["Section divider color"] = "區段分隔線顏色"
L["Global font"] = "全域字型"
L["Base font for all elements. Each module can override it."] = "所有元素的基礎字型。每個模組都可覆寫它。"
L["Pick a font, then click Apply to overwrite the font of every element."] =
    "選擇字型，然後點擊套用以覆寫所有元素的字型。"
L["Apply to all elements"] = "套用到所有元素"
L["Choose which properties are overwritten on every element."] = "選擇要在所有元素上覆寫的屬性。"
L["This overwrites the font of every element with the global font. Continue?"] =
    "這將以全域字型覆寫所有元素的字型。是否繼續？"
L["This overwrites the selected font properties of every element. Continue?"] =
    "這將覆寫所有元素所選的字型屬性。是否繼續？"
L["X offset"] = "X 偏移"
L["Y offset"] = "Y 偏移"
L["Bar"] = "進度條"
L["Bar width"] = "進度條寬度"
L["Bar height"] = "進度條高度"
L["0 = use the display width."] = "0 = 使用顯示寬度。"
L["Time text"] = "時間文字"
L["Text"] = "文字"
L["Dividers"] = "分隔線"
L["Divider color"] = "分隔線顏色"
L["Divider width"] = "分隔線寬度"
L["Section colors"] = "區段顏色"
L["Countdown label"] = "倒數計時文字"
L["Vertical position"] = "垂直位置"
L["Above"] = "上方"
L["Below"] = "下方"
L["Side of divider"] = "分隔線的一側"
L["Position"] = "位置"
L["Left of divider"] = "分隔線左側"
L["Right of divider"] = "分隔線右側"
L["In bar, left of divider"] = "進度條內，分隔線左側"
L["In bar, right of divider"] = "進度條內，分隔線右側"
L["Split bar into three"] = "將進度條分為三段"
L["Split bar at checkpoints"] = "在檢查點分割進度條"
L["Split the bar into segments at each checkpoint (the 100% target is ignored)."] =
    "在每個檢查點將進度條分成若干段（忽略 100% 目標）。"
L["Segment gap"] = "分段間隙"
L["Segment countdown"] = "分段倒數計時"
L["Segment percentage"] = "分段百分比"
L["Show the still-needed percentage on each segment (split bar) or at each checkpoint marker; it counts down and hides when the checkpoint is reached."] =
    "在每個分段（分割進度條）或每個檢查點標記處顯示仍需的百分比；它會倒數並在到達檢查點時隱藏。"
L["All checkpoint countdowns"] = "所有檢查點倒數計時"
L["Show Enemy Forces row"] = "顯示敵軍數量行"
L["Show percentage text"] = "顯示百分比文字"
L["Show the forces percentage (and remaining count) text on the bar."] =
    "在進度條上顯示敵軍百分比（及剩餘數量）文字。"
L["Add an Enemy Forces entry at the end of the list: live percentage while in progress, completion time once done."] =
    "在清單末尾新增一個敵軍數量項目：進行中顯示即時百分比，完成後顯示完成時間。"
L["Show a countdown to every checkpoint at once, not just the next."] =
    "同時顯示到每個檢查點的倒數計時，而不僅僅是下一個。"
L["Bar-text spacing"] = "進度條—文字間距"
L["Vertical space between the time text and the bar."] = "時間文字與進度條之間的垂直間距。"
L["Show three segments (+3 large, +2 and +1 small) instead of one bar."] =
    "顯示三個分段（+3 大，+2 和 +1 小）而非單一進度條。"
L["Colors"] = "顏色"
L["All element colors, grouped by area."] = "所有元素顏色，依區域分組。"
L["All section countdowns"] = "所有區段倒數計時"
L["Show a countdown to every section threshold (+3/+2/+1) at once, not just the next."] =
    "同時顯示到每個區段閾值（+3/+2/+1）的倒數計時，而不僅僅是下一個。"
L["Show keystone level"] = "顯示鑰石等級"
L["Show the keystone level next to the dungeon name."] = "在地城名稱旁顯示鑰石等級。"
L["Level position"] = "等級位置"
L["Color by level rarity"] = "依等級品質著色"
L["Color the keystone level with Blizzard's rarity color."] = "使用暴雪的品質顏色為鑰石等級著色。"
L["Separator line"] = "分隔線"
L["Show a separator between the dungeon name and the level."] = "在地城名稱和等級之間顯示一條分隔線。"
L["Top left"] = "左上"
L["Top right"] = "右上"
L["Bottom left"] = "左下"
L["Bottom right"] = "右下"
L["Alignment"] = "對齊"
L["Default text alignment (each module can override this)."] = "預設文字對齊方式（每個模組都可覆寫）。"
L["Text alignment for this element."] = "此元素的文字對齊方式。"
L["Inherit"] = "繼承"
L["Left"] = "靠左"
L["Center"] = "置中"
L["Right"] = "靠右"
L["Timer"] = "計時器"
L["Enable"] = "啟用"
L["Toggle demo"] = "切換展示"
L["Section countdown"] = "區段倒數計時"
L["Show the remaining time until the current +3/+2 threshold on its marker."] =
    "在標記處顯示距目前 +3/+2 閾值的剩餘時間。"
L["Enemy Forces"] = "敵軍數量"
L["Objectives"] = "目標"
L["Deaths"] = "死亡次數"
L["Splits"] = "分段時間"
L["Storage mode"] = "儲存模式"
L["Keep only the best time per dungeon/level, or a full history."] =
    "每個地城/等級僅保留最佳時間，或保留完整歷史紀錄。"
L["Best time only"] = "僅最佳時間"
L["Full history"] = "完整歷史紀錄"
L["Manage times"] = "管理時間"
L["Best"] = "最佳"
L["Boss"] = "首領"
L["No data"] = "無資料"
L["Delete this level"] = "刪除此等級"
L["Delete dungeon"] = "刪除地城"
L["Removes all stored times for this dungeon (every key level). Cannot be undone."] =
    "刪除此地城所有已儲存的時間（每個鑰石等級）。無法復原。"
L["Removes only this run."] = "僅刪除此次紀錄。"
L["Run vs best"] = "本次 vs 最佳"
L["Checkpoints"] = "檢查點"
L["Time"] = "時間"
L["Edit checkpoints"] = "編輯檢查點"
L["Dungeon"] = "地城"
L["Dungeon name"] = "地城名稱"
L["Affixes"] = "詞綴"
L["Show affixes"] = "顯示詞綴"
L["Checkpoint markers"] = "檢查點標記"
L["Show checkpoint markers"] = "顯示檢查點標記"
L["Mark the checkpoint target percentages on the bar."] = "在進度條上標記檢查點目標百分比。"
L["Marker color"] = "標記顏色"
L["Sample dungeon"] = "範例地城"
L["Sample affixes"] = "殘暴，強韌"
L["Select a dungeon."] = "選擇一個地城。"
L["Boss section targets"] = "首領區段目標"
L["Target %"] = "目標 %"
L["Remove"] = "移除"
L["Add boss target"] = "新增首領目標"
L["Point of No Return"] = "無法回頭點"
L["PoNR"] = "PoNR"
L["Minimum %"] = "最低 %"
L["Add point of no return"] = "新增無法回頭點"
L["Click Export to generate a shareable string of all your checkpoints, then copy it."] =
    "點擊匯出以產生所有檢查點的可分享字串，然後複製它。"
L["Paste a string and accept to import checkpoints."] = "貼上字串並確認以匯入檢查點。"
L["Import checkpoints? Matching dungeons will be overwritten."] = "匯入檢查點？符合的地城將被覆寫。"
L["Imported checkpoints for %d dungeon(s)."] = "已為 %d 個地城匯入檢查點。"
L["Load default checkpoints"] = "載入預設檢查點"
L["Load the author's curated checkpoint targets. Matching dungeons will be overwritten."] =
    "載入作者精選的檢查點目標。符合的地城將被覆寫。"
L["Overwrite matching dungeons with the built-in checkpoints?"] = "以內建檢查點覆寫符合的地城？"
L["Sound"] = "音效"
L["Death"] = "死亡"
L["Forces complete"] = "敵軍完成"
L["Time expired"] = "時間耗盡"
L["Run completed"] = "執行完成"
L["Checkpoint reached"] = "到達檢查點"
L["Heroism active"] = "英勇啟用"
L["Heroism"] = "英勇"
L["Cooldowns"] = "冷卻"
L["Battle resurrections"] = "戰鬥復活"
L["Show available battle resurrections and the recharge timer."] = "顯示可用的戰鬥復活次數及充能計時。"
L["Heroism availability"] = "英勇可用性"
L["Show when Heroism/Bloodlust is available again."] = "顯示英勇/嗜血何時再次可用。"
L["Time position"] = "時間位置"
L["Where the boss split time is shown relative to the name."] = "首領分段時間相對於名稱的顯示位置。"
L["Automatic (follow alignment)"] = "自動（跟隨對齊）"
L["Left of name"] = "名稱左側"
L["Right of name"] = "名稱右側"
-- Objectives: boss-name shortening
L["Shorten boss names"] = "縮短首領名稱"
L["How boss names are shortened for display; internally the full name is always kept."] =
    "首領名稱如何縮短顯示；內部始終保留完整名稱。"
L["Off"] = "關閉"
L["Truncate with ellipsis"] = "截斷（…）"
L["First word only"] = "僅第一個詞"
L["Abbreviate following words"] = "縮寫後續詞語"
L["Max characters"] = "最大字元數"
L["Names longer than this are cut and end with an ellipsis."] = "超過此長度的名稱將被截斷並以刪節號結尾。"
